import React, { useState, useEffect } from 'react'
import axios from 'axios'

const C = {
  bg:'#13131b',bgDeep:'#0a0a12',surface:'#1b1b23',surfaceMid:'#1f1f27',
  surfaceHigh:'#292932',primary:'#ffb1c0',primaryCont:'#ff4c83',
  secondary:'#00e0b3',tertiary:'#e3c630',error:'#ffb4ab',errorCont:'#93000a',
  outline:'#5b3f44',textMain:'#e4e1ed',textMuted:'#e4bdc3',
}

const lbl = { 
  fontFamily:'Space Grotesk,sans-serif',fontSize:10,
  color:'rgba(228,189,195,0.55)',letterSpacing:'0.15em',textTransform:'uppercase'
}

export default function MLDatasetView() {
  const [data, setData] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    // Fetch only the REAL, live transactions generated by the payment app from MongoDB
    axios.get('/api/db-transactions?limit=500')
      .then(res => {
        setData(res.data.transactions || [])
        setLoading(false)
      })
      .catch(err => {
        console.error(err)
        setLoading(false)
      })
  }, [])

  return (
    <div style={{ width: '100%', height: '100%', padding: '80px 40px 40px', overflowY: 'auto', background: C.bgDeep, color: C.textMain }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 24 }}>
        <div>
          <h2 style={{ fontFamily: 'Sora,sans-serif', fontSize: 24, fontWeight: 800, color: C.secondary, margin: '0 0 8px' }}>ML Feature Dataset</h2>
          <p style={{ ...lbl, margin: 0 }}>Raw device intelligence payload for model training</p>
        </div>
        <div style={{ fontFamily: 'JetBrains Mono,monospace', fontSize: 12, color: C.textMuted }}>
          {data.length} RECORDS FOUND
        </div>
      </div>

      {loading ? (
        <div style={{ textAlign: 'center', marginTop: 100, fontFamily: 'Space Grotesk', color: C.primary }}>EXTRACTING DATA...</div>
      ) : (
        <div style={{ background: C.surface, border: `1px solid ${C.outline}`, borderRadius: 8, overflow: 'hidden' }}>
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
              <thead>
                <tr style={{ background: C.surfaceMid, borderBottom: `1px solid ${C.outline}` }}>
                  {['TIMESTAMP', 'TXN ID', 'SENDER', 'AMOUNT', 'IP / ISP', 'FP HASH', 'EMULATOR / PROXY', 'WEBGL RENDERER'].map(h => (
                    <th key={h} style={{ padding: '12px 16px', ...lbl, color: C.textMuted }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {data.map((tx, i) => (
                  <tr key={tx.transaction_id || i} style={{ borderBottom: `1px solid ${C.outline}44`, background: i % 2 === 0 ? 'transparent' : C.surfaceLow }}>
                    <td style={{ padding: '12px 16px', fontFamily: 'JetBrains Mono,monospace', fontSize: 11, color: C.textMuted }}>
                      {tx.timestamp ? new Date(tx.timestamp.endsWith('Z') ? tx.timestamp : tx.timestamp + 'Z').toLocaleString() : '—'}
                    </td>
                    <td style={{ padding: '12px 16px', fontFamily: 'JetBrains Mono,monospace', fontSize: 11, color: C.secondary }}>
                      {tx.transaction_id ? tx.transaction_id.slice(-8) : '—'}
                    </td>
                    <td style={{ padding: '12px 16px', fontFamily: 'Inter,sans-serif', fontSize: 12, color: C.textMain }}>
                      {tx.sender_upi || '—'}
                    </td>
                    <td style={{ padding: '12px 16px', fontFamily: 'Sora,sans-serif', fontSize: 12, fontWeight: 700, color: C.textMain }}>
                      ₹{(tx.amount || 0).toLocaleString()}
                    </td>
                    <td style={{ padding: '12px 16px', fontFamily: 'JetBrains Mono,monospace', fontSize: 11, color: C.textMuted }}>
                      <div style={{ color: C.textMain }}>{tx.sender_ip || '—'}</div>
                      <div style={{ fontSize: 9 }}>{tx.isp || '—'}</div>
                    </td>
                    <td style={{ padding: '12px 16px', fontFamily: 'JetBrains Mono,monospace', fontSize: 11, color: C.tertiary }}>
                      {tx.device_fingerprint ? tx.device_fingerprint.slice(0, 16) + '...' : '—'}
                    </td>
                    <td style={{ padding: '12px 16px', fontFamily: 'Inter,sans-serif', fontSize: 11 }}>
                      {tx.emulator_flags?.length > 0 || tx.emulator_used ? (
                        <span style={{ background: 'rgba(255,180,171,0.1)', color: C.error, padding: '2px 6px', borderRadius: 4, marginRight: 6 }}>EMULATOR</span>
                      ) : null}
                      {tx.is_proxy ? (
                        <span style={{ background: 'rgba(255,177,192,0.1)', color: C.primaryCont, padding: '2px 6px', borderRadius: 4 }}>PROXY</span>
                      ) : null}
                      {!tx.emulator_flags?.length && !tx.emulator_used && !tx.is_proxy && (
                        <span style={{ color: C.textMuted }}>Clean</span>
                      )}
                    </td>
                    <td style={{ padding: '12px 16px', fontFamily: 'JetBrains Mono,monospace', fontSize: 10, color: C.textMuted, maxWidth: 200, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                      {tx.webgl_renderer || '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {data.length === 0 && (
              <div style={{ padding: 40, textAlign: 'center', color: C.textMuted, fontFamily: 'Inter,sans-serif' }}>
                No records found.
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
